/**
  	BASIC FUNCTIONALITY
	-----------------------------------
	- Make map with custom CRS
	- Load CSV data for land plot polygons
	- Load CSV data for land circles
	- Load CSV marker data on hover
	- Color code CSV data based on use
 */// var tileJSON = $.get('http://api.tiles.mapbox.com/v1/castavridis.ghee5le5');
/* CONSTANTS ***************************/function percentInView(){viewableArea=0;$.get("_/php/parcels.php",function(e){var t=map.getBounds();for(var n=e.length-1;n>=0;n--){var r=e[n],i=r.polygon;i=i.replace("POLYGON ((","").replace("))","");var s=i.split(","),o=[];for(var u=0;u<s.length;u++){var a=s[u].replace("(","").replace(")","").split(" "),f=a[1],l=a[0];o.push(L.latLng(f,l))}var c=L.polyline(o,{}).getBounds();t.contains(c)&&(viewableArea+=polygonArea(o))}});return viewableArea/totalArea*100}function getBubbles(){$.get("_/php/bubbles.php",function(e){var t=L.featureGroup().addTo(map),n={stroke:!1,fillColor:"#F90",fillOpacity:.125};for(var r=e.length-1;r>=0;r--){var i=e[r],s=i.id,o=i.x,u=i.y,a=100;L.circle([u,o],a,n).addTo(t)}})}function getParcels(){$.get("_/php/parcels.php",function(e){var t=L.featureGroup().addTo(map),n={stroke:!1,fillColor:"#09F",fillOpacity:.25,smoothFactor:0,showArea:!0};for(var r=e.length-1;r>=0;r--){var i=e[r],s=i.id,o=i.polygon,u=i.handle,a=i.parcel_id;o=o.replace("POLYGON ((","").replace("))","");var f=o.split(","),l=[];for(var c=0;c<f.length;c++){var h=f[c].replace("(","").replace(")","").split(" "),p=h[1],d=h[0];l.push(L.latLng(p,d))}totalArea+=polygonArea(l);L.polygon(l,n).addTo(t)}})}function polygonArea(e){var t=0,n=e.length-1;for(var r=0;r<e.length;r++){var i=e[r],s=e[n];t+=(Math.abs(i.lat)+Math.abs(s.lat))*(Math.abs(i.lng)+Math.abs(s.lng));n=r}return t/2}var TILE_JSON="http://a.tiles.mapbox.com/v1/castavridis.ghee5le5.json",map,totalArea=0;$(document).ready(function(){map=L.mapbox.map("map-view",TILE_JSON,{minZoom:12,maxZoom:17,maxBounds:[[38.5322,-90.4188],[38.7425,-90.0728]]});getBubbles();getParcels()});var viewableArea;